data_dir: '/Users/ridasaghir/Documents/Datasets/UrbanSound8K'
num_classes: 10
sample_rate: 16000
target_duration: 4.0
embedding_dim: 1024
broadcast_interval: 1
base_url: "http://localhost:8000"
check_point : "model_checkpoint.pth"
human_annotations: "human_annotations.json"
learning_rate : 1e-3
batch_size : 32
per_class_count : 20
num_annotation_suggestions : 5
num_iterations : 50
